### ISSUE TITLE
Ugly divider between tab bar and content in VS 2013 and Windows 8.1

### ISSUE THREAD

**Issue by parkertomatoes** [lstratman/EasyTabs#12]
There is a blue tab that cuts into the tab and tab text when I tried the test application in Windows 8.1. 
![image](https://cloud.githubusercontent.com/assets/6298931/3562577/1a9d3940-09f8-11e4-9905-7961ebfd1237.png)

**Comment by xposure** [comment]
I have experienced the same issue on Windows 7. While your Caption Text is rather large and this doesn't address that, for anyone else looking, I had to make these changes. I'm not sure what these changes will do on other versions of the Windows OS.

TitleBarTabsOverlay.cs

		/// <summary>Sets the position of the overlay window to match that of <see cref="_parentForm" /> so that it moves in tandem with it.</summary>
		protected void OnPosition()
		{
			if (!IsDisposed)
			{
				// If the form is in a non-maximized state, we position the tabs below the minimize/maximize/close
				// buttons
				Top = _parentForm.Top + (DisplayType == DisplayType.Classic
					? SystemInformation.VerticalResizeBorderThickness
					: _parentForm.WindowState == FormWindowState.Maximized
						? 10 /* SystemInformation.VerticalResizeBorderThickness */
						: SystemInformation.CaptionHeight + 4);
                Left = _parentForm.Left + SystemInformation.HorizontalResizeBorderThickness - SystemInformation.BorderSize.Width + 8;
				Width = _parentForm.Width - (SystemInformation.VerticalResizeBorderThickness * 2) + (SystemInformation.BorderSize.Width * 2) - 8;
				Height = _parentForm.TabRenderer.TabHeight + (DisplayType == DisplayType.Classic && _parentForm.WindowState != FormWindowState.Maximized
					? SystemInformation.CaptionButtonSize.Height
					: 0);

				Render();
			}
		}

**Comment by lstratman** [comment]
This is a .NET 4.0 vs. .NET 4.5 app issue regarding how the framework reports certain UI metrics that EasyTabs uses to position the overlay (see https://connect.microsoft.com/VisualStudio/feedback/details/763767/the-systemparameters-windowresizeborderthickness-seems-to-return-incorrect-value for details).  I've updated the code and the latest version of the NuGet package deals with this issue in a framework-independent way.
