### ISSUE TITLE
Transparency of Tabs

### ISSUE THREAD

**Issue by losubo** [lstratman/EasyTabs#13]
Hi, I just want to report a small issue that I solved it myself. By changing the form.opacity of the main window tabs continue to be completely opaque. With this small change tabs follows parent's transparency. 

File: TitleBarTabsOverlay.cs
Function: Render
Change: SourceConstantAlpha = 255
To: (byte)(_parentForm.Opacity \* 255)

That's all. Thank you for sharing this excellent component.

**Comment by lstratman** [comment]
Thanks!  This has been merged into the codebase and will show up in the NuGet package in the next few days.
