### ISSUE TITLE
It can be compiled in XP + VS2010.But can not run.

### ISSUE THREAD

**Issue by zbooa** [lstratman/EasyTabs#14]
It can be compiled in XP + VS2010.But can not run.
This is Message:
"Unable to find entry point called "Attribute SetWindowTheme" in DLL "uxtheme.dll"."
I think it's a XP template problem, but can be modified to support XP ?
I think you can do it .Waiting for you.Give you kiss.

**Comment by lstratman** [comment]
Sorry, XP is not a supported operating system.
