### ISSUE TITLE
Error when create new tab programmaticaly

### ISSUE THREAD

**Issue by Brainiac24** [lstratman/EasyTabs#15]
Can't create new tab programmaticaly it says thread error in `Content.Parent = Parent;` in 143 line in TitleBarTab.cs file. How create new tab programmaticaly?

**Comment by ghostknow** [comment]
same question here, anyone have solution?

**Comment by lstratman** [comment]
If you are creating the new tab outside of the UI thread for the application, you have to use Form.Invoke() to run that action on the UI thread.  Something like:

```cs
tabsForm.Invoke(() =>
{
    // This can also be an action to create a tab for programatically and add it to the tabs collection
    tabsForm.CreateTab();
});
```

Sorry for the delay in replying, if you're still using this library, let me know if this fixes your issue.
