### ISSUE TITLE
how to create a new tab that do not show the icon in windows taskbar

### ISSUE THREAD

**Issue by don59** [lstratman/EasyTabs#16]
how to create a new tab that do not show the icon in windows taskbar? I want all tabs just show one icon in the windows taskbar like easyconnect.
![1](https://user-images.githubusercontent.com/8613083/31920760-9a16e002-b89d-11e7-90e5-042e22bd67a5.png)
![2](https://user-images.githubusercontent.com/8613083/31920866-2d8d4bfa-b89e-11e7-8cae-2f3af721d28c.png)

**Comment by new1271** [comment]
VB:
Me.AeroPeekEnabled = False
C#:
this.AeroPeekEnabled = false;
