### ISSUE TITLE
necessary suggestion

### ISSUE THREAD

**Issue by tigros** [lstratman/EasyTabs#18]
i had mouse issues, it was too slow if busy or w/e, you definitely need to add this in TitleBarTabsOverlay.cs: 

_mouseEventsThread.Priority = ThreadPriority.Highest;

Thanks a bunch for this project! love it!

**Comment by lstratman** [comment]
This was merged in #4 and will show up in the NuGet package in the next few days.

**Comment by tigros** [comment]
heh Thanks! I later found out that putting the SetWindowsHookEx also in it's own high priority thread helps alot too, but I'm dealing with major amounts of threads so not needed in typical situations.
I can pass you that if you're interested.
Have a look at what I did with your code, https://integritech.ca if you find it useful anyone reading this and trying it just send me HID I'll send you back mysys.lic free! no problemo!

**Comment by tigros** [comment]
I just remembered tho putting SetWindowsHookEx in it's own thread caused odd low fps in at least 1 game Grid autosport, so you need to unhook when app is deactivated, in other words maybe forget I mentioned it it's too risky :) cheers!
