### ISSUE TITLE
Closing program after closing last tab

### ISSUE THREAD

**Issue by jacksiro254** [lstratman/EasyTabs#19]
I noticed when I closed the last tab or I simply close the entire program, it does not exit entirely but continues to stay in the background till I have to close with the task manager. Kindly help fix this or give us a hint on how to resolve this.

**Comment by vlogozzo** [comment]
+1

**Comment by lstratman** [comment]
I haven't been able to reproduce this on my side using either my test application or the other project I have that uses this library.  What does your main form class look like and what does the `Main()` method for your application look like?

**Comment by lstratman** [comment]
Closing this out since I wasn't able to reproduce.
