### ISSUE TITLE
EasyTabs + CefSharp. Open link in new tab

### ISSUE THREAD

**Issue by H0d3ine** [lstratman/EasyTabs#20]
When you open a link from Google, a new window opens.
How to make it so that when you click on the link, the page opens in a new tab
Screenshot: https://pp.userapi.com/c845421/v845421640/1cba8d/5VF9-SF7aIo.jpg

**Comment by Haltroy** [comment]
This seems to be a `CefSharp` related problem, not `EasyTabs`.
[This](https://stackoverflow.com/a/30557700) can solve your problem.

**Comment by lstratman** [comment]
The test app now also uses CefSharp for its rendering engine and it opens popups in new tabs using the approach in the link provided by @Haltroy  above.
