### ISSUE TITLE
Ability to change colors

### ISSUE THREAD

**Issue by Haltroy** [lstratman/EasyTabs#24]
Hi,
Is there a way to change colors?
I want to change tab color on ChromeTabRenderer but I could not manage to find  anything regarding to "Color".

**Comment by Haltroy** [comment]
My question is similar to #22 but I want more than just dark and light mode. I want to change it to any color.

**Comment by Haltroy** [comment]
I figured it out.
To do this, we need to recolor every image (or create those images with code) and then use it.
I'm trying to turn those images into a code so when we need to use them we can just draw those and turn those drawings to an image that can be used by BaseTabRenderer.

**Comment by Haltroy** [comment]
I managed to recolor them in a code using these codes:

    
private static int LowerBrightnessIfNeeded(int defaultint, int lower) => defaultint > lower ? defaultint - lower : defaultint;
    
    
        private static int MoreBrightnessIfNeeded(int defaultint, int add, int limit) => defaultint + add > limit ? defaultint : defaultint + add;
    
    
        private static bool IsBright(Color c){return (int)Math.Sqrt(c.R * c.R * .241 +c.G * c.G * .691 +c.B * c.B * .068) > 130 ? true : false;}
    
    
        public static Image ColorReplace(Image inputImage, int tolerance, Color oldColor, Color NewColor)
        {
            Bitmap outputImage = new Bitmap(inputImage.Width, inputImage.Height);
            Graphics G = Graphics.FromImage(outputImage);
            G.DrawImage(inputImage, 0, 0);
            for (Int32 y = 0; y < outputImage.Height; y++)
                for (Int32 x = 0; x < outputImage.Width; x++)
                {
                    Color PixelColor = outputImage.GetPixel(x, y);
                    if (PixelColor.R > oldColor.R - tolerance && PixelColor.R < oldColor.R + tolerance && PixelColor.G > oldColor.G - tolerance && PixelColor.G < oldColor.G + tolerance && PixelColor.B > oldColor.B - tolerance && PixelColor.B < oldColor.B + tolerance)
                    {
                        int RColorDiff = oldColor.R - PixelColor.R;
                        int GColorDiff = oldColor.G - PixelColor.G;
                        int BColorDiff = oldColor.B - PixelColor.B;

                        if (PixelColor.R > oldColor.R) RColorDiff = NewColor.R + RColorDiff;
                        else RColorDiff = NewColor.R - RColorDiff;
                        if (RColorDiff > 255) RColorDiff = 255;
                        if (RColorDiff < 0) RColorDiff = 0;
                        if (PixelColor.G > oldColor.G) GColorDiff = NewColor.G + GColorDiff;
                        else GColorDiff = NewColor.G - GColorDiff;
                        if (GColorDiff > 255) GColorDiff = 255;
                        if (GColorDiff < 0) GColorDiff = 0;
                        if (PixelColor.B > oldColor.B) BColorDiff = NewColor.B + BColorDiff;
                        else BColorDiff = NewColor.B - BColorDiff;
                        if (BColorDiff > 255) BColorDiff = 255;
                        if (BColorDiff < 0) BColorDiff = 0;

                        outputImage.SetPixel(x, y, Color.FromArgb(RColorDiff, GColorDiff, BColorDiff));
                    }
                }
            return outputImage;
        } 
    
Now we only need to use those in a shape like this:
     
            _activeLeftSideImage = IsBright(BackColor) ? ColorReplace(Resources.ChromeLeft, 50, Color.White, Color.FromArgb(255, LowerBrightnessIfNeeded(BackColor.R, 30), LowerBrightnessIfNeeded(BackColor.G, 30), LowerBrightnessIfNeeded(BackColor.B, 30))) : ColorReplace(Resources.ChromeLeft,50,Color.White,Color.FromArgb(255,MoreBrightnessIfNeeded(BackColor.R,30,255), MoreBrightnessIfNeeded(BackColor.G, 30, 255), MoreBrightnessIfNeeded(BackColor.B, 30, 255)));

     

Now I'm working on to enable changing colors on runtime.

**Comment by Haltroy** [comment]
I finished it.
[Here's the files that I changed.](http://haltroy.com/EasyTabs-Color-Code.zip)
(Writing every change on here would take more time than making those changes.)

I removed Inactive tab images because I can just adjust brightness and they will be faded out.
I also did some changes to images directly to remove ugly-looking color problems.
(I also replaced CloseButton and it's hover image and used CloseButton.So there will be a red circle around it but I adjusted it's brightness on hover.)

[Here's my Resource folder (if anyone is interested in).](http://haltroy.com/EasyTabs-Color-Resources.zip)

**Comment by Haltroy** [comment]
Just add an option to change text color. We can do the rest easily.

**Comment by savronix-zz** [comment]
Bunu yapamadım bana yardım eder misin? || I couldn't do this can you help me?

**Comment by Haltroy** [comment]
> Bunu yapamadım bana yardım eder misin? || I couldn't do this can you help me?

Artık ben burayı (WinForms işini) bıraktım ama kısaca söyleyim. Şu [BaseTabRenderer](https://github.com/lstratman/EasyTabs/blob/master/BaseTabRenderer.cs) class'ını inheritleyip kendi override [`Render()`](https://github.com/lstratman/EasyTabs/blob/0688cee00d9a8a05c1b3797b70ec8e4d035fa4d4/BaseTabRenderer.cs#LL531C4-L531C4) kodumu yazıp oluşturduğum class'ı kullandım. Koddaki yorumlar baya işe yarıyor. Önerim direk o resimleri yazdırmak yerine `FillRectangle` , `FillPath` vs. gibi komutlarla el ile çizdirmek böylece istediğin rengi kullanabilirsin.

I stopped using this (and WinForms stuff) but in short I inherited my own [BaseTabRenderer](https://github.com/lstratman/EasyTabs/blob/master/BaseTabRenderer.cs) class and override [`Render()`](https://github.com/lstratman/EasyTabs/blob/0688cee00d9a8a05c1b3797b70ec8e4d035fa4d4/BaseTabRenderer.cs#LL531C4-L531C4) method and used the class I made instead. Comments inside the code did help a lot. My recommendation is to not use images but use commands like `FillRectangle` , `FillPath` vs. so you can customize their colors more easily.

**Comment by Haltroy** [comment]
Also muting this, Luke is dead lol
