### ISSUE TITLE
FormClosing Event

### ISSUE THREAD

**Issue by thedroid** [lstratman/EasyTabs#26]
It seems that the FormClosing / FormClosed events for the tabs are never called when the application is closed from the main form's close(X) button.  The events do get called if closed using the tab's close(X) button.   Is there a way to intercept the main close button event?

**Comment by thedroid** [comment]
Sorted by modifying TitleBarTabs.cs to make TitleBarTabs a protected virtual, so that we can subscribe to it using ParentTabs.FormClosing += ParentFormClosing.

**Comment by lstratman** [comment]
This has been officially released in the 2.0.0 version of the package that I just deployed.
