### ISSUE TITLE
How to make new tab?

### ISSUE THREAD

**Issue by Rondell9451** [lstratman/EasyTabs#28]
So I'm using this, works tremendously, however the only issue I encountered is how do I make a new tab ?

So, I have my regular tab, and [when I make a new tab by clicking the + button it creates a replica of the main tab. ](https://i.gyazo.com/5bbeba14ead0e52511f014f54242806d.mp4), like it suppose to do, however, [how do I fix it so when I click like 'Configurations' it shows a different page?](https://i.gyazo.com/e7bd992fa67c8066e83ca835eb420fa8.png)

I've looked over the 'Similar Issues' and none of which is helpful to me.

**Comment by Haltroy** [comment]
Well, you have to implement it by yourself.
Duplicate the `CreateTab()` in same for but add a new parameter. Use `if` for that parameter.

    public void CreateTab(bool Config)
    {
    TitleBarTab newTab;
        if (Config) 
        {
          newTab = new TitleBarTab(this)
            {
                Content = new frmConfig
            };
         } else {
            newTab = new TitleBarTab(this)
            {
                Content = new Form1
            };
         }
            this.Tabs.Add(newTab);
    }

Also, you can use parameters for those `Content`s too.

    public void CreateTab(bool Config)
    {
    TitleBarTab newTab;
          newTab = new TitleBarTab(this)
            {
                Content = new Form1(Config)
            };
            this.Tabs.Add(newTab);
    }
Second one requires new parameters for the main tab form

    public class tabform : Form 
    {
        bool ConfigurationMode = false;
        public TitleBarTabs ParentTabs => (ParentForm as TitleBarTabs);
        public frmMain mainform()
        {
         return ((frmMain)this.ParentTabs);
        }
        public tabform (bool isConfig) 
        {
            ConfigurationMode = isConfig;
            // rest of the code....

You can call it like this:

    mainform().Invoke(new Action(() => 
    {
     mainform().CreateTab(true); //Creates tab
//NOTE: You can put more codes in here if you want.
    }));

or (for just creating tabs, no more extra codes to `Invoke()`)

    mainform().Invoke(new Action(() => mainform().CreateTab(true)));

###### Detect if your main form is not disposed or closing before executing `Invoke` commands.

**Comment by lstratman** [comment]
@Haltroy is right on the money (thanks!), so I'm closing this out.

**Comment by KairoMartins18** [comment]
I didn't really understand how to add a new tab with a different form
