### ISSUE TITLE
Issue Title Tab context menu and UI cannot restore from Maximized to Normal properly

### ISSUE THREAD

**Issue by maihcx** [lstratman/EasyTabs#29]
I found the problem on the tab's context menu
When I right click, it will crash if I select Close on the menu. Again, the UI cannot restore the correct location from Maximize to Normal if I move the form to the top screen.

**Comment by lstratman** [comment]
The fix for closing from the titlebar context menu is in the codebase and will be in a beta version of the NuGet package that I'll publish in the next day or so.

**Comment by lstratman** [comment]
This has been officially released in the 2.0.0 version of the package that I just deployed.
