### ISSUE TITLE
How to change tab name?

### ISSUE THREAD

**Issue by TheReactiveMouse** [lstratman/EasyTabs#32]
How to change tab name? I'm making my browser, i'm need after loading page, change tab name to web site title.

**Comment by bobowk** [comment]
This one's easy.
this.ParentTabs.SelectedTab.Caption = text.Text

**Comment by prima-facie** [comment]
@bobowk Can you explain a little bit more? This one doesn't work for me.

**Comment by lstratman** [comment]
@bobowk is right on.  You can also get a specific tab from the `Tabs` property of `TitleBarTabs` and set properties of specific tabs that way or set the `Text` property of the content form being displayed in the tab and redraw the tabs by calling `TitleBarTabs.RedrawTabs()`.

**Comment by spacebytee** [comment]
this.ParentTabs.SelectedTab.Caption = text.Text

What class is "this" referring to and how can I get it from another class, this is reallly annoying and I'm kind of confused and frustrated by how EasyTabs works since there's not much clarification here.
