### ISSUE TITLE
How to make custom tab renderer?

### ISSUE THREAD

**Issue by TheClashFruit** [lstratman/EasyTabs#34]
I want to make custom tabs like firefox

**Comment by Haltroy** [comment]
You can change the images (from Resources) or draw them yourself (by using [`BaseTabRenderer.cs`](https://github.com/lstratman/EasyTabs/blob/master/BaseTabRenderer.cs) or customizing that file and using customized BaseTabRenderer as renderer).

**Comment by Haltroy** [comment]
I noticed that my answer wasn't that much clear. So sorry about that.
First, create a class in your project (ex. MyCustomTabRenderer.cs) and add ` : BaseTabRenderer` next to `class [YourClassName]`

      ...
      using EasyTabs;
      namespace MyApp 
      {
         class MyCustomTabRenderer : BaseTabRenderer 
         {
            public MyCustomTabRenderer(TitleBarTabs parentWindow) : base(parentWindow) 
            {
               // You can change images here like tihs:
               _activeLeftSideImage = Resources.MyCustomTabLeft;
            }
         }
      }
   
You can check out [`ChromeTabRenderer.cs`](https://github.com/lstratman/EasyTabs/blob/master/ChromeTabRenderer.cs) class as example for your custom tab renderer.

And then apply the new custom renderer to your form by changing `TabRenderer` property to your custom tab renderer.

     ...
    [Your Form Constructor, ex: public frmMain()]
    { 
        ...
       TabRenderer = new MyCustomTabRenderer(this);
      ...
