### ISSUE TITLE
Show Icon In Taskbar

### ISSUE THREAD

**Issue by shawon0709** [lstratman/EasyTabs#35]
Hello

Is there any way to show only one TabForm in taskbar instead of multiple tab

Thanks

![Untitled](https://user-images.githubusercontent.com/12869065/82739237-d937fb00-9d5f-11ea-8037-32aa8a51d0bf.png)

**Comment by lstratman** [comment]
Yes, set the `AeroPeekEnabled` property of your form class that inherits from `EasyTabs.TitleBarTabs` to `false`.  This will simply display the contents of the window in the titlebar instead of thumbnails for each tab.
