### ISSUE TITLE
Tooltip code not in latest Nuget package

### ISSUE THREAD

**Issue by slprogrp** [lstratman/EasyTabs#39]
Hi there,

I can see the tooltip code in the master branch, but it is not in the latest Nuget Package.
In VS 2019 when I Manage Nuget Packages and search for EasyTabs it says the Latest Package is 1.3.3 and it was published on the Sep 10 2017.  This does not include the tooltip code.

Is there any chance you could update nuget to the latest code please?

**Comment by lstratman** [comment]
Yep, I'm back working on this project after a long time away from it.  I've just published a beta version of the package with the look and feel from the latest Chrome and also the tooltips code.  Feel free to download it and let me know if you run into any problems.  I'm going to take a few days to integrate it with another project of mine for final testing, after which point I'll publish an "official" 2.0.0 version.

**Comment by slprogrp** [comment]
Luke,

Thanks for the update, this is great news!
Can I add this to the list as it seems that when you close the main application the OnFormClosing event is not raised on forms loaded into EasyTabs.
I found this issue on it:
https://github.com/lstratman/EasyTabs/issues/26

I tried the suggested work around but it didn't work for me.

**Comment by slprogrp** [comment]
Oh and this would be a great one to fix as well :-)

Closing program after closing last tab #19

**Comment by lstratman** [comment]
That issue should now be resolved in the latest 2.0.0-beta2 version of the NuGet package that I just published.

**Comment by slprogrp** [comment]
Luke,

Thanks for the update.  I put in the NuGet package but when I start my app I get the following error:

Could not load file or assembly 'Svg, Version=2.4.3.29446, Culture=neutral, PublicKeyToken=12a0bac221edeae2' or one of its dependencies. The system cannot find the file specified.

With the stacktrace:

   at EasyTabs.WindowsSizingBoxes.LoadSvg(String svgXml, Int32 width, Int32 height)
   at EasyTabs.WindowsSizingBoxes..ctor(TitleBarTabs parentWindow)
   at EasyTabs.ChromeTabRenderer..ctor(TitleBarTabs parentWindow)
   at ePASClientAssistBrowser.EPASAppContainer..ctor() in C:\git\Source\MyApp\MyAppContainer.cs:line 22
   at ePASClientAssistBrowser.Program.Main(String[] args) in C:\git\Source\MyApp\Program.cs:line 74

That was using 2.0.0-beta4

**Comment by lstratman** [comment]
Sorry, my bad, didn't have the `Svg` package listed as a dependency in the .nuspec.  This should now be resolved in the beta5 package that I just published.

**Comment by lstratman** [comment]
This has been officially released in the 2.0.0 version of the package that I just deployed.
