### ISSUE TITLE
Add tooltip support

### ISSUE THREAD

**Issue by lstratman** [lstratman/EasyTabs#4]
Add the ability to display tooltips for tabs.

**Comment by tigros** [comment]
i did this, here it is.
[TitleBarTabs.zip](https://github.com/lstratman/EasyTabs/files/1872187/TitleBarTabs.zip)

**Comment by lstratman** [comment]
Thanks for the contribution!  Sorry it took me so long to integrate it, but it should show up in the NuGet package in the next few days.
