### ISSUE TITLE
Create new tab in new windows

### ISSUE THREAD

**Issue by maihcx** [lstratman/EasyTabs#42]
Hi, how i can create tab in new window ?

**Comment by maihcx** [comment]
So, i can do it. I add my code in TitleBarTabs.cs

    public virtual void AddTabToNewWindow(TitleBarTab tab)
        {
            TitleBarTab _tornTab = tab;
            TitleBarTabs newWindow = (TitleBarTabs)Activator.CreateInstance(this.GetType());

            Screen screen = Screen.AllScreens.First(s => s.WorkingArea.Contains(Cursor.Position));

            newWindow.StartPosition = FormStartPosition.Manual;

            if (this.WindowState == FormWindowState.Maximized)
            {
                newWindow.WindowState = this.WindowState;
                newWindow.Left = screen.WorkingArea.Left;
                newWindow.Top = screen.WorkingArea.Top;
            }
            else
            {
                newWindow.Width = this.Size.Width;
                newWindow.Height = this.Size.Height;
                newWindow.Left = this.Location.X + 40;
                newWindow.Top = this.Location.Y + 40;
            }

            _tornTab.Parent = newWindow;
            this.ApplicationContext.OpenWindow(newWindow);

            newWindow.Show();
            newWindow.Tabs.Add(_tornTab);
            newWindow.SelectedTabIndex = 0;
            newWindow.ResizeTabContents();
     }

**Comment by lstratman** [comment]
Yes, that's the standard way to do this.  You actually don't need to modify the source of the `TitleBarTabs` class, you can simply add this method to your application's `Form` class that inherits from `TitleBarTabs`.
