### ISSUE TITLE
How to get browser url a tabs text and icon

### ISSUE THREAD

**Issue by jarno9981** [lstratman/EasyTabs#55]
!help   

How to get browser url and icon in the tabs bar text and icon   ,  example go to youtube.com = tabs youtube icon + youtube.com

**Comment by jarno9981** [comment]
@lstratman   ?? How to get url name and icon in the tabs

**Comment by lstratman** [comment]
The sample project for this project already does this, for the both the site’s favicon and its title, so look at the sample browser application code included in this repository if you want to see how to do that.

________________________________

**Comment by jarno9981** [comment]
Oke i will look into it
