### ISSUE TITLE
Please add .net 5 support 

### ISSUE THREAD

**Issue by jarno9981** [lstratman/EasyTabs#62]
Can you add .net 5 support

**Comment by jarno9981** [comment]
@lstratman can you add .net 5 support

**Comment by billqian** [comment]
It would be great if .net core was supported

**Comment by 0orc** [comment]
> It would be great if .net core was supported

I also.

**Comment by jarno9981** [comment]
> 

I made a copy of the repo with .net 5 support but still in alpha on nuget

**Comment by jarno9981** [comment]
> > It would be great if .net core was supported
> 
> I also.

I made a copy of the repo with .net 5 support but still in alpha on nuget

@0orc

**Comment by jarno9981** [comment]
@billqian i added 
.net 5 support on costum nuget name : FireTabsNet5

**Comment by billqian** [comment]
> @billqian i added .net 5 support on costum nuget name : FireTabsNet5

It's great, but it seems different from this project, not a simple copy, I am testing it... thanks!

**Comment by jarno9981** [comment]
@billqian 

Or look add this project
https://github.com/jarno9981/FireBrowser

In the second form
protected FireTitle ParentTabs
        {
            get
            {
                return (ParentForm as FireTitle);
            }
        }

First form
TabRenderer = new FireTabRenderer(this);

public override FireTitleTab CreateTab() { return new FireTitleTab(this) { Content = new BrowserWindow { Text = "Fire Browser" } }; }


public partial class WebContainer : FireTitle

Program.cs

container.Tabs.Add(
                // Our First Tab created by default in the Application will have as content the Form1
                new FireTitleTab(container)
                {
                    Content = new BrowserWindow
                    {
                        Text = "Fire Browser"
                    }
                }
            );





            // Set initial tab the first one
            container.SelectedTabIndex = 0;

            // Create tabs and start application
            FireTitleApplicationContext applicationContext = new FireTitleApplicationContext();
            applicationContext.Start(container);
            Application.Run(applicationContext);

**Comment by billqian** [comment]
@jarno9981  Thanks so much, working on...

**Comment by jarno9981** [comment]
@billqian  its still a alpha version so you may come accros some bugs  Note x64 only

**Comment by jarno9981** [comment]
@billqian 

https://github.com/jarno9981/FireTabsNet5  

the opensource repo

**Comment by jarno9981** [comment]
@billqian please make a bug report if you come accros any bug

**Comment by jarno9981** [comment]
@billqian if you want you can help and i give you write and read acces the repo

**Comment by billqian** [comment]
> @billqian if you want you can help and i give you write and read acces the repo

thanks very much, but I think I don't have enough time, I will send you message if I think I readlly can help it. thanks!

**Comment by jarno9981** [comment]
@billqian i you find any issues please report in repo
