### ISSUE TITLE
Custom Tab Renderers

### ISSUE THREAD

**Issue by spacebytee** [lstratman/EasyTabs#69]
Hi! I;'m trying to make a custom tab renderer, but I'm most likely missing something, since there's not much information about how to use easytabs online I'd figure I'd ask here, sorry for askign so many questions of here. I'm probably missing something huge but I'm just not sure what I need, whenever I try to run my program with this tab renderer I get an error, I believe it was a NullReferenceException? Thanks for the help.
`using Browser2.Properties;
    using EasyTabs;
        public class CrapTabRenderer : BaseTabRenderer
        {
            public CrapTabRenderer(TitleBarTabs parentWindow) : base(parentWindow)
            {
                _activeLeftSideImage = global::Browser2.Properties.Resources.Left;
                _activeRightSideImage = global::Browser2.Properties.Resources.Right;
                _activeCenterImage = global::Browser2.Properties.Resources.Center;
            }
        }`

**Comment by jarno9981** [comment]
@bytespacegames 

Try constructor like this

public TabStyle(TitleBarTabs parentWindow) : base(parentWindow) { // Your custom code here }

**Comment by bytespacegames** [comment]
> 
> 
> @bytespacegames
> 
> Try constructor like this
> 
> public TabStyle(TitleBarTabs parentWindow) : base(parentWindow) { // Your custom code here }

It says it needs a return type, what do I return with?

**Comment by spacebytee** [comment]
> 
> 
> @bytespacegames
> 
> Try constructor like this
> 
> public TabStyle(TitleBarTabs parentWindow) : base(parentWindow) { // Your custom code here }

I still get the error: "Object reference is not set to an instance of an object", why is this happening?

**Comment by spacebytee** [comment]
Fixed: Issue was that I needed to set literally everything, you need to have a file for each one, you can't just override stuff and leave the rest blank

**Comment by jarno9981** [comment]
@bytespacegames  okay
