### ISSUE TITLE
Сhange the color of a tab

### ISSUE THREAD

**Issue by maksmkv** [lstratman/EasyTabs#70]
Hi everyone. How do I change the color of a tab? thank you.

**Comment by jarno9981** [comment]
@maksmkv is based on image the color make a contructor to change ut

public TabStyle(TitleBarTabs parentWindow) : base(parentWindow) 

{ 

// Your custom code here 

}

**Comment by maksmkv** [comment]
> @maksmkv is based on image the color make a contructor to change ut
> 
> public TabStyle(TitleBarTabs parentWindow) : base(parentWindow)
> 
> {
> 
> // Your custom code here
> 
> }

Thank's

**Comment by lstratman** [comment]
Thanks to @jarno9981 for the answer, closing this out.

**Comment by jarno9981** [comment]
> Thanks to @jarno9981 for the answer, closing this out.

@lstratman 
Will you update the easytabs libabry so its fits windows 11
